[phases.setup]
nixPkgs = ["bun"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[phases.dev]
cmds = ["bun run dev"]

[start]
cmd = "bun run start"
